In [ ]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [ ]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.52665174,  0.6877829 , -0.16452938, -1.1131428 , -0.19707212,
         0.00967626,  0.6293341 , -0.22757229,  0.06163085,  0.6869957 ]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.13639478, 0.16024192, 0.06833161, 0.0264633 , 0.0661437 ,
        0.08133513, 0.15114443, 0.06415676, 0.08567256, 0.16011582]],
      dtype=float32)

Define a loss function for training using `losses.SparseCategoricalCrossentropy`:

In [ ]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.5091772

In [ ]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2905 - accuracy: 0.9166
Epoch 2/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.1437 - accuracy: 0.9568
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1078 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0873 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0755 - accuracy: 0.9766


In [ ]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0741 - accuracy: 0.9788 - 917ms/epoch - 3ms/step


[0.07407195121049881, 0.9787999987602234]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.0282438e-07, 3.5801705e-08, 8.5814809e-06, 8.5289990e-05,
        2.4359159e-11, 2.7842219e-08, 4.4914166e-14, 9.9990559e-01,
        4.9346873e-08, 1.4112287e-07],
       [5.3639244e-08, 8.9573832e-06, 9.9982363e-01, 1.6687778e-04,
        5.9260925e-14, 9.4885387e-08, 5.4710196e-09, 2.2873134e-12,
        4.5837939e-07, 1.9512618e-13],
       [8.3701252e-07, 9.9878627e-01, 2.0587377e-04, 1.8459306e-05,
        4.0097617e-05, 6.9839348e-06, 6.0247468e-05, 4.8387170e-04,
        3.9349560e-04, 3.8377570e-06],
       [9.9990535e-01, 4.0709514e-10, 3.5221699e-05, 2.1768094e-06,
        7.9610778e-08, 1.1822175e-05, 1.6869475e-05, 1.1437036e-05,
        2.8598438e-07, 1.6717138e-05],
       [5.0103718e-06, 4.0677026e-09, 1.1892241e-05, 7.1680746e-09,
        9.9901533e-01, 2.7335187e-07, 1.0009578e-06, 3.6533591e-05,
        1.1731160e-07, 9.2986453e-04]], dtype=float32)>

#PROBLEM 2

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

# Load dataset
df = pd.read_csv("Iriss.csv")

# Condition extraction from data frame
df = df[(df["Species"] == "Iris-versicolor") | (df["Species"] == "Iris-virginica")]
y = df["Species"]
X = df.loc[:, ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]

# Convert labels to numbers
y[y == "Iris-versicolor"] = 0
y[y == "Iris-virginica"] = 1

# Convert to NumPy array
X = np.array(X)
y = np.array(y).astype(np.int64)

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
# Further split into train and val
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

# Hyperparameter settings
learning_rate = 0.001
batch_size = 10
num_epochs = 100

# Neural network model
model = Sequential()
model.add(Dense(50, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(100, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=num_epochs, batch_size=batch_size, validation_data=(X_val, y_val), verbose=1)

# Evaluate the model
test_loss, test_acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", test_acc)


Epoch 1/100


<ipython-input-28-2b2315966bae>:17: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y[y == "Iris-virginica"] = 1


7/7 [==============================] - 1s 36ms/step - loss: 0.6809 - accuracy: 0.7031 - val_loss: 0.6746 - val_accuracy: 0.5625
Epoch 2/100
7/7 [==============================] - 0s 7ms/step - loss: 0.6601 - accuracy: 0.6094 - val_loss: 0.6996 - val_accuracy: 0.3750
Epoch 3/100
7/7 [==============================] - 0s 8ms/step - loss: 0.6565 - accuracy: 0.5469 - val_loss: 0.6634 - val_accuracy: 0.4375
Epoch 4/100
7/7 [==============================] - 0s 7ms/step - loss: 0.6366 - accuracy: 0.5469 - val_loss: 0.6770 - val_accuracy: 0.3750
Epoch 5/100
7/7 [==============================] - 0s 9ms/step - loss: 0.6268 - accuracy: 0.5469 - val_loss: 0.6551 - val_accuracy: 0.3750
Epoch 6/100
7/7 [==============================] - 0s 7ms/step - loss: 0.6184 - accuracy: 0.5625 - val_loss: 0.6362 - val_accuracy: 0.6250
Epoch 7/100
7/7 [==============================] - 0s 10ms/step - loss: 0.6070 - accuracy: 0.6719 - val_loss: 0.6320 - val_accuracy: 0.5625
Epoch 8/100
7/7 [====================

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

# Load dataset
df = pd.read_csv("Iriss.csv")

# Condition extraction from data frame
y = df["Species"]
X = df.loc[:, ["SepalLengthCm", "SepalWidthCm", "PetalLengthCm", "PetalWidthCm"]]

# Convert labels to numbers
y = y.replace({"Iris-versicolor": 0, "Iris-virginica": 1, "Iris-setosa": 2})

# Convert to NumPy array
X = np.array(X)
y = np.array(y)

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

# Hyperparameter settings
learning_rate = 0.001
batch_size = 10
num_epochs = 100

# Neural network model
model = Sequential()
model.add(Dense(50, activation='relu', input_shape=(X_train.shape[1],)))
model.add(Dense(100, activation='relu'))
model.add(Dense(3, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train, epochs=num_epochs, batch_size=batch_size, validation_data=(X_val, y_val), verbose=1)

# Evaluate the model
test_loss, test_acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", test_acc)


Epoch 1/100
10/10 [==============================] - 3s 100ms/step - loss: 0.9499 - accuracy: 0.5521 - val_loss: 0.7929 - val_accuracy: 0.7083
Epoch 2/100
10/10 [==============================] - 0s 10ms/step - loss: 0.7458 - accuracy: 0.6875 - val_loss: 0.6657 - val_accuracy: 0.7083
Epoch 3/100
10/10 [==============================] - 0s 9ms/step - loss: 0.6332 - accuracy: 0.8125 - val_loss: 0.5767 - val_accuracy: 0.9167
Epoch 4/100
10/10 [==============================] - 0s 8ms/step - loss: 0.5305 - accuracy: 0.7708 - val_loss: 0.5115 - val_accuracy: 0.7083
Epoch 5/100
10/10 [==============================] - 0s 9ms/step - loss: 0.4686 - accuracy: 0.7083 - val_loss: 0.4650 - val_accuracy: 0.7083
Epoch 6/100
10/10 [==============================] - 0s 9ms/step - loss: 0.4232 - accuracy: 0.9479 - val_loss: 0.4358 - val_accuracy: 0.9167
Epoch 7/100
10/10 [==============================] - 0s 9ms/step - loss: 0.3931 - accuracy: 0.8750 - val_loss: 0.4164 - val_accuracy: 0.7083
Epoch 8/10

In [ ]:
#Load dataset
house_df = pd.read_csv("trainn.csv")
#Condition extraction from data frame
house_df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense

# Load dataset
house_df = pd.read_csv("trainn.csv")

# Condition extraction from data frame
_X = house_df[["GrLivArea", "YearBuilt"]].to_numpy()
_y = house_df[["SalePrice"]].to_numpy()

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(_X, _y, test_size=0.2, random_state=0)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=0)

# Hyperparameter settings
learning_rate = 0.001
batch_size = 10
num_epochs = 100

n_hidden1 = 50
n_hidden2 = 100
n_input = X_train.shape[1]
n_samples = X_train.shape[0]
n_classes = 1

# Neural network model
model = Sequential()
model.add(Dense(n_hidden1, activation='relu', input_shape=(n_input,)))
model.add(Dense(n_hidden2, activation='relu'))
model.add(Dense(n_classes))

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
history = model.fit(X_train, y_train, epochs=num_epochs, batch_size=batch_size, validation_data=(X_val, y_val), verbose=1)

# Evaluate the model
test_loss = model.evaluate(X_test, y_test)
print("Test MSE:", test_loss)


Epoch 1/100
94/94 [==============================] - 1s 4ms/step - loss: 36485804032.0000 - val_loss: 28570263552.0000
Epoch 2/100
94/94 [==============================] - 0s 2ms/step - loss: 17726076928.0000 - val_loss: 4918802432.0000
Epoch 3/100
94/94 [==============================] - 0s 3ms/step - loss: 4368418304.0000 - val_loss: 3346419456.0000
Epoch 4/100
94/94 [==============================] - 0s 2ms/step - loss: 4022499328.0000 - val_loss: 3233239296.0000
Epoch 5/100
94/94 [==============================] - 0s 3ms/step - loss: 3914947072.0000 - val_loss: 3184889088.0000
Epoch 6/100
94/94 [==============================] - 0s 2ms/step - loss: 3831995136.0000 - val_loss: 3068896768.0000
Epoch 7/100
94/94 [==============================] - 0s 3ms/step - loss: 3727465728.0000 - val_loss: 2971011584.0000
Epoch 8/100
94/94 [==============================] - 0s 2ms/step - loss: 3653877760.0000 - val_loss: 2878621696.0000
Epoch 9/100
94/94 [==============================] - 0s 2ms/s

In [ ]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from sklearn.preprocessing import OneHotEncoder

# Load dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Reshape and normalize data
X_train = X_train.reshape(-1, 784).astype('float32') / 255
X_test = X_test.reshape(-1, 784).astype('float32') / 255

# One-hot encode labels
enc = OneHotEncoder(sparse=False)
y_train_one_hot = enc.fit_transform(y_train.reshape(-1, 1))
y_test_one_hot = enc.transform(y_test.reshape(-1, 1))

# Hyperparameters
learning_rate = 0.001
batch_size = 10
num_epochs = 10
n_hidden1 = 50
n_hidden2 = 100
n_input = X_train.shape[1]
n_classes = 10

# Define the model
model = Sequential([
    Dense(n_hidden1, activation='relu', input_shape=(n_input,)),
    Dense(n_hidden2, activation='relu'),
    Dense(n_classes, activation='softmax')
])

# Compile the model
model.compile(optimizer=Adam(learning_rate), loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
history = model.fit(X_train, y_train_one_hot, epochs=num_epochs, batch_size=batch_size, validation_split=0.2)

# Evaluate the model
test_loss, test_acc = model.evaluate(X_test, y_test_one_hot)
print("Test loss:", test_loss)
print("Test accuracy:", test_acc)


/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Epoch 1/10
4800/4800 [==============================] - 18s 3ms/step - loss: 0.2633 - accuracy: 0.9219 - val_loss: 0.1568 - val_accuracy: 0.9520
Epoch 2/10
4800/4800 [==============================] - 12s 2ms/step - loss: 0.1261 - accuracy: 0.9611 - val_loss: 0.1282 - val_accuracy: 0.9592
Epoch 3/10
4800/4800 [==============================] - 19s 4ms/step - loss: 0.0929 - accuracy: 0.9717 - val_loss: 0.1175 - val_accuracy: 0.9636
Epoch 4/10
4800/4800 [==============================] - 22s 5ms/step - loss: 0.0763 - accuracy: 0.9758 - val_loss: 0.1148 - val_accuracy: 0.9678
Epoch 5/10
4800/4800 [==============================] - 13s 3ms/step - loss: 0.0616 - accuracy: 0.9805 - val_loss: 0.1087 - val_accuracy: 0.9697
Epoch 6/10
4800/4800 [==============================] - 13s 3ms/step - loss: 0.0549 - accuracy: 0.9829 - val_loss: 0.1237 - val_accuracy: 0.9693
Epoch 7/10
4800/4800 [==============================] - 14s 3ms/step - loss: 0.0474 - accuracy: 0.9849 - val_loss: 0.1364 - val_ac

#PROBLEM 8
When comparing TensorFlow and Keras, there are several aspects to consider:

Calculation Speed:

TensorFlow: TensorFlow offers high performance due to its efficient execution engine and support for distributed computing. It can leverage GPUs and TPUs for accelerated computation.
Keras: Keras, being a high-level API built on top of TensorFlow, can achieve similar performance to TensorFlow. However, it may have a slight overhead due to its abstraction layer.
Number of Lines of Code and Readability:

TensorFlow: TensorFlow typically requires more lines of code compared to Keras for building and training neural networks. Its low-level nature allows for fine-grained control but can make the code more verbose.

Keras: Keras emphasizes simplicity and readability. It abstracts away much of the complexity of TensorFlow, resulting in concise and intuitive code. It's well-suited for quick prototyping and experimentation.
Functions Provided:

TensorFlow: TensorFlow provides a comprehensive set of functionalities for building, training, and deploying machine learning models. It supports low-level operations, automatic differentiation, custom layers, and advanced features like distributed training and model serving.

Keras: Keras offers a user-friendly interface for building neural networks. It includes a wide range of predefined layers, activation functions, optimizers, and loss functions. Keras also supports custom layers and models, making it flexible for implementing novel architectures.

In summary, TensorFlow is more suitable for projects requiring fine-grained control and high-performance computing, while Keras excels in simplicity, readability, and rapid prototyping.
